/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarsRouteImport } from './routes/mars'
import { Route as LaunchesRouteImport } from './routes/launches'
import { Route as IssRouteImport } from './routes/iss'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ApodRouteImport } from './routes/apod'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicNewsRouteImport } from './routes/api/public/news'
import { Route as ApiPublicLaunchesRouteImport } from './routes/api/public/launches'
import { Route as ApiPublicApodRouteImport } from './routes/api/public/apod'

const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarsRoute = MarsRouteImport.update({
  id: '/mars',
  path: '/mars',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesRoute = LaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const IssRoute = IssRouteImport.update({
  id: '/iss',
  path: '/iss',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApodRoute = ApodRouteImport.update({
  id: '/apod',
  path: '/apod',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsRoute = ApiPublicNewsRouteImport.update({
  id: '/api/public/news',
  path: '/api/public/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLaunchesRoute = ApiPublicLaunchesRouteImport.update({
  id: '/api/public/launches',
  path: '/api/public/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApodRoute = ApiPublicApodRouteImport.update({
  id: '/api/public/apod',
  path: '/api/public/apod',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apod': typeof ApodRoute
  '/explore': typeof ExploreRoute
  '/iss': typeof IssRoute
  '/launches': typeof LaunchesRoute
  '/mars': typeof MarsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/api/public/apod': typeof ApiPublicApodRoute
  '/api/public/launches': typeof ApiPublicLaunchesRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apod': typeof ApodRoute
  '/explore': typeof ExploreRoute
  '/iss': typeof IssRoute
  '/launches': typeof LaunchesRoute
  '/mars': typeof MarsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/api/public/apod': typeof ApiPublicApodRoute
  '/api/public/launches': typeof ApiPublicLaunchesRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apod': typeof ApodRoute
  '/explore': typeof ExploreRoute
  '/iss': typeof IssRoute
  '/launches': typeof LaunchesRoute
  '/mars': typeof MarsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/api/public/apod': typeof ApiPublicApodRoute
  '/api/public/launches': typeof ApiPublicLaunchesRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apod'
    | '/explore'
    | '/iss'
    | '/launches'
    | '/mars'
    | '/news'
    | '/sitemap.xml'
    | '/solar'
    | '/api/public/apod'
    | '/api/public/launches'
    | '/api/public/news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apod'
    | '/explore'
    | '/iss'
    | '/launches'
    | '/mars'
    | '/news'
    | '/sitemap.xml'
    | '/solar'
    | '/api/public/apod'
    | '/api/public/launches'
    | '/api/public/news'
  id:
    | '__root__'
    | '/'
    | '/apod'
    | '/explore'
    | '/iss'
    | '/launches'
    | '/mars'
    | '/news'
    | '/sitemap.xml'
    | '/solar'
    | '/api/public/apod'
    | '/api/public/launches'
    | '/api/public/news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApodRoute: typeof ApodRoute
  ExploreRoute: typeof ExploreRoute
  IssRoute: typeof IssRoute
  LaunchesRoute: typeof LaunchesRoute
  MarsRoute: typeof MarsRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarRoute: typeof SolarRoute
  ApiPublicApodRoute: typeof ApiPublicApodRoute
  ApiPublicLaunchesRoute: typeof ApiPublicLaunchesRoute
  ApiPublicNewsRoute: typeof ApiPublicNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mars': {
      id: '/mars'
      path: '/mars'
      fullPath: '/mars'
      preLoaderRoute: typeof MarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches': {
      id: '/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof LaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iss': {
      id: '/iss'
      path: '/iss'
      fullPath: '/iss'
      preLoaderRoute: typeof IssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apod': {
      id: '/apod'
      path: '/apod'
      fullPath: '/apod'
      preLoaderRoute: typeof ApodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news': {
      id: '/api/public/news'
      path: '/api/public/news'
      fullPath: '/api/public/news'
      preLoaderRoute: typeof ApiPublicNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/launches': {
      id: '/api/public/launches'
      path: '/api/public/launches'
      fullPath: '/api/public/launches'
      preLoaderRoute: typeof ApiPublicLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apod': {
      id: '/api/public/apod'
      path: '/api/public/apod'
      fullPath: '/api/public/apod'
      preLoaderRoute: typeof ApiPublicApodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApodRoute: ApodRoute,
  ExploreRoute: ExploreRoute,
  IssRoute: IssRoute,
  LaunchesRoute: LaunchesRoute,
  MarsRoute: MarsRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarRoute: SolarRoute,
  ApiPublicApodRoute: ApiPublicApodRoute,
  ApiPublicLaunchesRoute: ApiPublicLaunchesRoute,
  ApiPublicNewsRoute: ApiPublicNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
