/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarsRouteImport } from './routes/mars'
import { Route as LaunchesRouteImport } from './routes/launches'
import { Route as IssRouteImport } from './routes/iss'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApodRouteImport } from './routes/apod'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicNewsRouteImport } from './routes/api/public/news'
import { Route as ApiPublicLaunchesRouteImport } from './routes/api/public/launches'
import { Route as ApiPublicBackdropRouteImport } from './routes/api/public/backdrop'
import { Route as ApiPublicApodRouteImport } from './routes/api/public/apod'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarsRoute = MarsRouteImport.update({
  id: '/mars',
  path: '/mars',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesRoute = LaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const IssRoute = IssRouteImport.update({
  id: '/iss',
  path: '/iss',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApodRoute = ApodRouteImport.update({
  id: '/apod',
  path: '/apod',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsRoute = ApiPublicNewsRouteImport.update({
  id: '/api/public/news',
  path: '/api/public/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLaunchesRoute = ApiPublicLaunchesRouteImport.update({
  id: '/api/public/launches',
  path: '/api/public/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackdropRoute = ApiPublicBackdropRouteImport.update({
  id: '/api/public/backdrop',
  path: '/api/public/backdrop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApodRoute = ApiPublicApodRouteImport.update({
  id: '/api/public/apod',
  path: '/api/public/apod',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apod': typeof ApodRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/iss': typeof IssRoute
  '/launches': typeof LaunchesRoute
  '/mars': typeof MarsRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/apod': typeof ApiPublicApodRoute
  '/api/public/backdrop': typeof ApiPublicBackdropRoute
  '/api/public/launches': typeof ApiPublicLaunchesRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apod': typeof ApodRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/iss': typeof IssRoute
  '/launches': typeof LaunchesRoute
  '/mars': typeof MarsRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/apod': typeof ApiPublicApodRoute
  '/api/public/backdrop': typeof ApiPublicBackdropRoute
  '/api/public/launches': typeof ApiPublicLaunchesRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apod': typeof ApodRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/iss': typeof IssRoute
  '/launches': typeof LaunchesRoute
  '/mars': typeof MarsRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar': typeof SolarRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/apod': typeof ApiPublicApodRoute
  '/api/public/backdrop': typeof ApiPublicBackdropRoute
  '/api/public/launches': typeof ApiPublicLaunchesRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apod'
    | '/auth'
    | '/explore'
    | '/iss'
    | '/launches'
    | '/mars'
    | '/mcp'
    | '/news'
    | '/sitemap.xml'
    | '/solar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/apod'
    | '/api/public/backdrop'
    | '/api/public/launches'
    | '/api/public/news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apod'
    | '/auth'
    | '/explore'
    | '/iss'
    | '/launches'
    | '/mars'
    | '/mcp'
    | '/news'
    | '/sitemap.xml'
    | '/solar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/apod'
    | '/api/public/backdrop'
    | '/api/public/launches'
    | '/api/public/news'
  id:
    | '__root__'
    | '/'
    | '/apod'
    | '/auth'
    | '/explore'
    | '/iss'
    | '/launches'
    | '/mars'
    | '/mcp'
    | '/news'
    | '/sitemap.xml'
    | '/solar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/apod'
    | '/api/public/backdrop'
    | '/api/public/launches'
    | '/api/public/news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApodRoute: typeof ApodRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  IssRoute: typeof IssRoute
  LaunchesRoute: typeof LaunchesRoute
  MarsRoute: typeof MarsRoute
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarRoute: typeof SolarRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicApodRoute: typeof ApiPublicApodRoute
  ApiPublicBackdropRoute: typeof ApiPublicBackdropRoute
  ApiPublicLaunchesRoute: typeof ApiPublicLaunchesRoute
  ApiPublicNewsRoute: typeof ApiPublicNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mars': {
      id: '/mars'
      path: '/mars'
      fullPath: '/mars'
      preLoaderRoute: typeof MarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches': {
      id: '/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof LaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iss': {
      id: '/iss'
      path: '/iss'
      fullPath: '/iss'
      preLoaderRoute: typeof IssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apod': {
      id: '/apod'
      path: '/apod'
      fullPath: '/apod'
      preLoaderRoute: typeof ApodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news': {
      id: '/api/public/news'
      path: '/api/public/news'
      fullPath: '/api/public/news'
      preLoaderRoute: typeof ApiPublicNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/launches': {
      id: '/api/public/launches'
      path: '/api/public/launches'
      fullPath: '/api/public/launches'
      preLoaderRoute: typeof ApiPublicLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backdrop': {
      id: '/api/public/backdrop'
      path: '/api/public/backdrop'
      fullPath: '/api/public/backdrop'
      preLoaderRoute: typeof ApiPublicBackdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apod': {
      id: '/api/public/apod'
      path: '/api/public/apod'
      fullPath: '/api/public/apod'
      preLoaderRoute: typeof ApiPublicApodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApodRoute: ApodRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  IssRoute: IssRoute,
  LaunchesRoute: LaunchesRoute,
  MarsRoute: MarsRoute,
  McpRoute: McpRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarRoute: SolarRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicApodRoute: ApiPublicApodRoute,
  ApiPublicBackdropRoute: ApiPublicBackdropRoute,
  ApiPublicLaunchesRoute: ApiPublicLaunchesRoute,
  ApiPublicNewsRoute: ApiPublicNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
